Добавлен основной сервис
AlexandraLesnykh/java-explore-with-me pull request #4
Opened 2023-06-08 09:17 UTC by AlexandraLesnykh

2023-06-09 11:11 UTC, AlexandraLesnykh commented
Основной сервис диплома. 1 итерация.

2023-06-09 21:15 UTC, db-exp requested changes

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/exceptions/ErrorHandler.java
> +    StringWriter sw = new StringWriter();
private final оба )

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/event/service/EventPublicService.java
> +    public EventPublicService(EventRepository eventRepository, CategoryRepository categoryRepository, RequestRepository requestRepository, StatClient statClient) {
можно просто AllArgsConstructor аннотацию

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/event/service/EventPublicService.java
> +        endpointHitDto.setIp(request.getRemoteAddr());
лучше сразу как параметр из контроллера передать, чтобы на уровне сервиса с request не работать

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(254)                            NOT NULL UNIQUE,
много) - 100 достаточно

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/resources/schema.sql
> +    status       VARCHAR(512)                            NOT NULL,
очень много - статус же маленький - можно вообще число из enum'а хранить

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/resources/application.properties
> +stats-server.url=http://stats-server:9090
лучше тоже как переменную закинуть

2023-06-09 21:15 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/validator/EmailValidation.java
> +public @interface EmailValidation {
стандартная аннотация Email не подошла?

2023-06-10 08:17 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/exceptions/ErrorHandler.java
> +    StringWriter sw = new StringWriter();
Сделано

2023-06-10 08:20 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/event/service/EventPublicService.java
> +    public EventPublicService(EventRepository eventRepository, CategoryRepository categoryRepository, RequestRepository requestRepository, StatClient statClient) {
Это у меня сначала StatClient не хотел запускаться, а с этой аннотацией ошибки видно не было. 
Добавила аннотацию)

2023-06-10 08:25 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/event/service/EventPublicService.java
> +        endpointHitDto.setIp(request.getRemoteAddr());
Сделано

2023-06-10 08:26 UTC, AlexandraLesnykh commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(254)                            NOT NULL UNIQUE,
Сделано

2023-06-10 08:27 UTC, AlexandraLesnykh commented on ewm-service/src/main/resources/schema.sql
> +    status       VARCHAR(512)                            NOT NULL,
Сделано

2023-06-10 08:30 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/validator/EmailValidation.java
> +public @interface EmailValidation {
В спецификации есть ограничения на количество символов в каждой из частей email. Решила, что проще будет создать свою аннотацию. Другой вариант не придумала)

2023-06-10 11:40 UTC, AlexandraLesnykh commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(254)                            NOT NULL UNIQUE,
Количество символов в  имени и почте указаны в спецификации - как раз таки 250 и 254 соответственно. Не могу уменьшить

2023-06-10 11:40 UTC, AlexandraLesnykh commented on ewm-service/src/main/resources/application.properties
> +stats-server.url=http://stats-server:9090
сделано

2023-06-10 11:50 UTC, AlexandraLesnykh commented
Итерация 2 основной части диплома

2023-06-10 15:51 UTC, db-exp commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(254)                            NOT NULL UNIQUE,
понял, странно)

2023-06-10 15:51 UTC, db-exp approved these changes

2023-06-12 12:12 UTC, merged