Добавлена функциональность комментирования
AlexandraLesnykh/java-explore-with-me pull request #5
Opened 2023-06-13 19:40 UTC by AlexandraLesnykh

2023-06-13 20:48 UTC, AlexandraLesnykh commented
Этап 3 дипломного проекта. Итерация 1.

2023-06-14 19:18 UTC, db-exp requested changes

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
не используется переменная user, если просто для проверки существования, то переменная не нужна
Можно сделать метод checkUser, а можно просто удалить переменную

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
так же как выше

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        Event event = eventPublicService.findById(eventId);
так же как выше

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
так же как выше

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/resources/application.properties
> -spring.datasource.username=${POSTGRES_USER}
а зачем удалила переменные?

2023-06-14 19:18 UTC, db-exp commented on stat-service/stat-server/src/main/resources/application.properties
> -spring.datasource.url=j${DB_URL}
давай вернем?

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/event/mapper/EventMapper.java
чтобы маппер сделать совсем красивым можно добавить final к классу и сделать private конструктор без параметров

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/dto/NewCommentDto.java
> +@SuperBuilder
тут же нет наследования и обычного Builder-а должно хватить

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/dto/UpdatedCommentDto.java
> +@SuperBuilder
тут же нет наследования и обычного Builder-а должно хватить

2023-06-14 19:18 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +@SuperBuilder
тут же нет наследования и обычного Builder-а должно хватить

2023-06-15 06:46 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
Да, это для проверки существования. Удалила переменные.

2023-06-15 06:46 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
Сделано

2023-06-15 06:47 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        Event event = eventPublicService.findById(eventId);
Сделано

2023-06-15 06:47 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentService.java
> +        User user = userService.findById(userId);
Сделано

2023-06-15 06:48 UTC, AlexandraLesnykh commented on ewm-service/src/main/resources/application.properties
> -spring.datasource.username=${POSTGRES_USER}
Недоглядела. Исправляла ошибки, запуская локально, и настройки обратно не вернула как было. Исправила.

2023-06-15 06:48 UTC, AlexandraLesnykh commented on stat-service/stat-server/src/main/resources/application.properties
> -spring.datasource.url=j${DB_URL}
Исправила

2023-06-15 06:50 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/event/mapper/EventMapper.java
Сделано

2023-06-15 06:52 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/dto/NewCommentDto.java
> +@SuperBuilder
Сделано

2023-06-15 06:52 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/dto/UpdatedCommentDto.java
> +@SuperBuilder
Сделано

2023-06-15 06:52 UTC, AlexandraLesnykh commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +@SuperBuilder
Сделано

2023-06-15 07:24 UTC, AlexandraLesnykh commented
Итерация 2. Поправлен CommentServise, исправлены аннотации в классах dto комментариев. Исправлены настройки application.properties

2023-06-15 08:10 UTC, db-exp approved these changes

2023-06-19 10:55 UTC, merged